# Generated by Django 5.0.7 on 2024-08-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("price", models.IntegerField()),
                (
                    "discount_per",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("rating", models.IntegerField(default=0)),
                ("image", models.ImageField(null=True, upload_to="images")),
            ],
        ),
    ]
