# Generated by Django 5.0.7 on 2024-08-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_discount_per_coffee_discount_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coffee",
            old_name="discount_price",
            new_name="discount_percentage",
        ),
    ]
