# Generated by Django 5.0.7 on 2024-08-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_discount_price_coffee_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="best_seller",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
